name: Docker Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ github.event.repository.name }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: print credentials
      run: env
      shell: bash
      # uses: docker/login-action@v3
      # run: |
      #   docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      # shell: bash
      # with:
      #   username: $DOCKER_USERNAME
      #   password: $DOCKER_PASSWORD
    
    # - name: Build and Push
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ env.DOCKER_IMAGE }}:${{ env.REPO_NAME }}